plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/openclaw/.openclaw/workspace/skills/second-brain"
publishOrigin = "default"
base = "/home/openclaw/.openclaw/workspace/skills/second-brain"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]